# Generated by Django 2.2.3 on 2019-07-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_order_orderprocessingdates_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': []},
        ),
    ]
