# Generated by Django 2.2.3 on 2019-07-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_auto_20190728_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='e-courier', max_length=100)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='OrderProcessingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Request Price'), (1, 'Query Result Submitted'), (2, 'Place Order'), (3, 'product purchased'), (4, 'product in shipping'), (5, 'product arrived in eZon office'), (6, 'product delivered to the customer'), (7, 'order completed'), (8, 'order canceled'), (9, 'order refunded'), (10, 'product defected')], default=0, help_text='Oder status')),
                ('date', models.DateField(auto_now=True)),
                ('notes', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='product_company',
            field=models.IntegerField(blank=True, choices=[(0, 'Amazon'), (1, 'Ebay'), (2, 'Walmart'), (3, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_country',
            field=models.IntegerField(blank=True, choices=[(0, 'USA'), (1, 'UK'), (2, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Request Price'), (1, 'Query Result Submitted'), (2, 'Place Order'), (3, 'product purchased'), (4, 'product in shipping'), (5, 'product arrived in eZon office'), (6, 'product delivered to the customer'), (7, 'order completed'), (8, 'order canceled'), (9, 'order refunded'), (10, 'product defected')], default=0, help_text='order status', max_length=1),
        ),
        migrations.DeleteModel(
            name='OrderProcessingDates',
        ),
        migrations.AddField(
            model_name='orderprocessingdate',
            name='oder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order_management.Order'),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order_management.Order'),
        ),
    ]
