# Generated by Django 2.2.3 on 2019-07-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_auto_20190727_0554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderprocessingdates',
            options={'ordering': ['date']},
        ),
    ]
