# Generated by Django 2.2.3 on 2019-07-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_auto_20190729_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='note',
            new_name='admin_note',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_note',
            field=models.TextField(blank=True, help_text='Please provide a detail description(size, color,..etc) for your product', max_length=1000, null=True),
        ),
    ]
