# Generated by Django 2.2.3 on 2019-07-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_auto_20190727_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_price',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Origin Amazon product price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_service_fee',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Service fee for the product', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_tax',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Tax for the product', max_digits=10),
        ),
    ]
