# Generated by Django 2.2.3 on 2019-07-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_auto_20190801_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprocessingdate',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
