# Generated by Django 2.2.3 on 2019-07-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_auto_20190801_0356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-probable_product_handover_date', 'status']},
        ),
    ]
