# Generated by Django 2.2.3 on 2019-07-31 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_auto_20190801_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderprocessingdate',
            old_name='oder',
            new_name='order',
        ),
    ]
