# Generated by Django 2.2.3 on 2019-07-31 23:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0011_auto_20190801_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprocessingdate',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 31, 23, 4, 10, 74387, tzinfo=utc)),
        ),
    ]
