# Generated by Django 2.2.3 on 2019-07-31 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0012_auto_20190801_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprocessingdate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
