# Generated by Django 2.2.3 on 2019-07-31 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0014_auto_20190801_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderprocessingdate',
            name='notes',
        ),
    ]
