# Generated by Django 2.2.3 on 2019-08-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0015_remove_orderprocessingdate_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_company',
            field=models.CharField(blank=True, choices=[('amazon', 'Amazon'), ('ebay', 'Ebay'), ('walmart', 'Walmart'), ('others', 'Others')], default='amazon', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_country',
            field=models.IntegerField(blank=True, choices=[('usa', 'USA'), ('uk', 'UK'), ('others', 'Others')], default='usa', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('price_query', 'Price Query'), ('query_result_submitted', 'Query Result Submitted'), ('placed_order', 'Placed Order'), ('product_purchased', 'product purchased'), ('product_in_shipping', 'product in shipping'), ('product_arrived_in_ezon_office', 'product arrived in eZon office'), ('product_delivered_to_the_customer', 'product delivered to the customer'), ('order_completed', 'order completed'), ('order_canceled', 'order canceled'), ('order_refunded', 'order refunded'), ('order_defected', 'product defected')], default='price_query', help_text='order status', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderprocessingdate',
            name='status',
            field=models.CharField(choices=[('price_query', 'Price Query'), ('query_result_submitted', 'Query Result Submitted'), ('placed_order', 'Placed Order'), ('product_purchased', 'product purchased'), ('product_in_shipping', 'product in shipping'), ('product_arrived_in_ezon_office', 'product arrived in eZon office'), ('product_delivered_to_the_customer', 'product delivered to the customer'), ('order_completed', 'order completed'), ('order_canceled', 'order canceled'), ('order_refunded', 'order refunded'), ('order_defected', 'product defected')], default='price_query', help_text='Order status', max_length=50),
        ),
    ]
