# Generated by Django 2.2.3 on 2019-08-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0016_auto_20190802_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_country',
            field=models.CharField(blank=True, choices=[('usa', 'USA'), ('uk', 'UK'), ('others', 'Others')], default='usa', max_length=50, null=True),
        ),
    ]
