# Generated by Django 2.2.3 on 2019-08-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0018_auto_20190802_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_payment_complete',
        ),
        migrations.RemoveField(
            model_name='paymentdates',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('partially_paid', 'Partially Paid'), ('full_paid', 'Full Paid')], default='not_paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentdates',
            name='payment_way',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('bkash', 'bKash'), ('card', 'Card'), ('bank', 'Bank')], max_length=40),
        ),
    ]
