# Generated by Django 2.2.3 on 2019-08-04 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0022_auto_20190804_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprocessingdate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status_dates', to='order_management.Order'),
        ),
    ]
