# Generated by Django 2.2.3 on 2019-08-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0024_orderprocessingdate_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('price_query', 'Price Query'), ('query_result_submitted', 'Query Result Submitted'), ('placed_order', 'Placed Order'), ('product_purchase_request', 'Product Purchase Request'), ('product_purchased', 'product purchased'), ('purchase_canceled', 'Purchase Canceled'), ('product_in_shipping', 'Product in Shipping'), ('product_arrived_in_ezon_office', 'Product Arrived In eZon Office'), ('product_delivered_to_the_customer', 'Product Delivered To The Customer'), ('order_completed', 'Order Completed'), ('order_canceled', 'Order Canceled'), ('order_refunded', 'Order Refunded'), ('order_defected', 'Product Defected')], default='price_query', help_text='Order status', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderprocessingdate',
            name='status',
            field=models.CharField(choices=[('price_query', 'Price Query'), ('query_result_submitted', 'Query Result Submitted'), ('placed_order', 'Placed Order'), ('product_purchase_request', 'Product Purchase Request'), ('product_purchased', 'product purchased'), ('purchase_canceled', 'Purchase Canceled'), ('product_in_shipping', 'Product in Shipping'), ('product_arrived_in_ezon_office', 'Product Arrived In eZon Office'), ('product_delivered_to_the_customer', 'Product Delivered To The Customer'), ('order_completed', 'Order Completed'), ('order_canceled', 'Order Canceled'), ('order_refunded', 'Order Refunded'), ('order_defected', 'Product Defected')], default='price_query', help_text='Order status', max_length=50),
        ),
    ]
