# Generated by Django 2.2.3 on 2019-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0026_auto_20190807_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
