# Generated by Django 2.2.3 on 2019-10-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0027_order_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='provider_name',
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_man_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
