# Generated by Django 2.2.3 on 2019-10-04 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_management', '0028_auto_20191004_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='delivery_man_name',
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='delivery_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
