# Generated by Django 2.2.3 on 2019-10-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0029_auto_20191004_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryinfo',
            old_name='delivery_man',
            new_name='delivery_person',
        ),
    ]
