# Generated by Django 2.2.6 on 2019-10-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0031_auto_20191012_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_service_fee',
            new_name='service_charge',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_tax',
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='shipping_address',
            field=models.CharField(default='69, west tejturi bazar', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='bd_custom',
            field=models.DecimalField(decimal_places=3, default=0, help_text='BD custom charge for the product', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='bd_shipping',
            field=models.DecimalField(decimal_places=3, default=0, help_text='BD shipping charge for the product', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Change rate of pound or dollar', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='foreign_shipping',
            field=models.DecimalField(decimal_places=3, default=0, help_text='USA or UK shipping charge for the product', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='foreign_tax',
            field=models.DecimalField(decimal_places=3, default=0, help_text='USA or UK tax for the product', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_or_bank_charge',
            field=models.DecimalField(decimal_places=3, default=0, help_text='mobile or bank charge', max_digits=10),
        ),
    ]
