# Generated by Django 2.2.6 on 2019-10-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0032_auto_20191015_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('dollar', 'Dollar'), ('pound', 'Pound')], default='dollar', max_length=50),
        ),
    ]
