# Generated by Django 2.2.6 on 2019-10-12 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191012_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phonenumberverification',
            name='count',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='phonenumberverification',
            name='verification_code',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
